export const START_LISTENING = 'START_LISTENING';
export const STOP_LISTENING = 'STOP_LISTENING';
export const FAILED_LISTENING = 'FAILED_LISTENING';
export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_FAILED = 'FETCH_DATA_FAILED';
export const FETCH_DATA_FULFILLED = 'FETCH_DATA_FULFILLED';
