# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pima', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='device',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Reading',
        ),
    ]
